name: 'kicad-exports'
description: 'exporting various files from #KiCAD via CI'
author: 'nerdyscout'
inputs:
  config:
    description: 'The plotting config file to use'
    required: true
  dir:
    description: 'The output directory [default: .]'
    required: false
    default: '.'
  board:
    description: 'The PCB .kicad-pcb board file [default: first *.kicad_pcb found]'
    required: false
    default: $(ls *.kicad_pcb | head -n1)
  schema:
    description: 'The schematic file (.sch) [default: first *.sch found]'
    required: false
    default: $(ls *.sch | head -n1)
runs:
  using: 'docker'
  image: 'Dockerfile'
#  image: docker://nerdyscout/kicad-exports:v2.0
  args:
    - -c ${{ inputs.config }}
    - -d ${{ inputs.dir }}
    - -b ${{ inputs.board }}
    - -e ${{ inputs.schema }}
branding:
  icon: 'cpu'
  color: 'green'