name: bom

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  bom:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports bom
      uses: ./
      with:
        config: bom.kibot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: bom"
      run: |
        test -f test/docs/bom/test*.html && \
        test -f test/docs/bom/test*.csv && \
        test -f test/docs/bom/test*.xlsx
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: bom
        path: test/docs/bom/*
